### ISSUE TITLE
Windows manifest doesn't match Sumo Logic documentation

### ISSUE THREAD

**Issue by jsilverman-blispay** [SumoLogic/sumo-collector-puppet-module#29]
In the windows manifest in this module, the installation dir appears to be C:\sumo\

However the docs state that the installer ends up in C:\Program Files\Sumo Logic Collector\ (or in the (x86) one

Questions

* Is C:\sumo\ just for downloading the installer?
* The docs state that user.properties is supposed to go into the installed dir. But this module has sumo.conf going into c:\sumo\. Please clarify what's going on here.

Thanks

**Comment by TerribleDev** [comment]
In the past, when these modules were authored, the sumo.config file was read from c:\sumo even if the collector was installed elsewhere. From what I can tell this behavior changed in [19.137](https://help.sumologic.com/Send-Data/Installed-Collectors/05Reference-Information-for-Collector-Installation/12sumo.conf-for-Legacy-Collectors)

The [new behavior](https://help.sumologic.com/Send-Data/Installed-Collectors/05Reference-Information-for-Collector-Installation/11Set-a-Collector-as-Ephemeral) is to drop a `user.properties` file in the same directory as the collector installation directory, if I'm reading the docs right.

So, I think this puppet module needs to be altered for the new non-legacy collector. Perhaps a boolean flag added called `UseLegacy = $false` so that existing users can opt into using the legacy collectors.

**Comment by arunpatyal** [comment]
The module has been updated:

- C:\sumo\ is used for downloading the installer and copy (from puppet master) the `sumoVarFile.txt` file which contains command line parameters for the installer.  This directory is also used to copy (from puppet master) or read sources.json/syncsources.json. 

- The `user.properties` is created by the installer using the `sumoVarFile.txt` file under the Program Files.

Let me know if any additional information is needed.
